// worker.ts (project root)
//
// The Worker generated by @opennextjs/cloudflare (.open-next/worker.js)
// only exports a `fetch` handler — no `scheduled` handler, so Cron Triggers
// configured in wrangler.toml previously had nothing listening for them.
// This is OpenNext's documented "Custom Worker" pattern: re-export the
// generated fetch handler unchanged, and add our own scheduled() alongside
// it. See: https://opennext.js.org/cloudflare/howtos/custom-worker
//
// Deliberately minimal and dependency-free — all real logic lives in Next.js
// API routes (self-fetched over plain HTTPS with the existing x-cron-secret
// auth pattern already used by every other /api/cron/* route), not here.
// Keeping this file trivial matters: it's the app's actual deployment entry
// point (wrangler.toml's `main`), so a bug here can break the whole app,
// not just one feature.

// @ts-ignore — .open-next/worker.js is generated at build time
import { default as handler } from './.open-next/worker.js';
import { deliverSlackJobNow, deliverEmailJobNow, NotificationJob } from './src/lib/notification-queue';
import { deliverZipJob, ZipJobMessage } from './src/lib/zip-jobs-queue';
import { applyR2Events, R2EventMessage } from './src/lib/drive/index-store';

const APP_URL = 'https://e8productions.com';

// Calls the app's own cron route handler directly, in-process — NOT via a
// real fetch() over the network. A Worker fetch()-ing its own public
// custom domain from inside scheduled() is a self-referential request back
// through Cloudflare's full edge pipeline (DNS, TLS, routing) to reach the
// very same Worker instance that's making the call; in practice this
// reliably produced 522 timeouts on every single cron tick. Since the
// OpenNext handler is already imported right here, we can just invoke
// handler.fetch(request, env, ctx) directly — identical Request in,
// identical Response out, zero network hop, so there's nothing to time out.
async function triggerCronRoute(path: string, env: any, ctx: ExecutionContext): Promise<void> {
  try {
    const request = new Request(`${APP_URL}${path}`, {
      method: 'POST',
      headers: { 'x-cron-secret': env.CRON_SECRET || '' },
    });
    const res: Response = await handler.fetch(request, env, ctx);
    if (!res.ok) {
      console.error(`[worker.ts] ${path} returned ${res.status}: ${await res.text().catch(() => '')}`);
    }
  } catch (err: any) {
    console.error(`[worker.ts] ${path} failed:`, err.message || err);
  }
}

export default {
  fetch: handler.fetch,

  async scheduled(controller: ScheduledController, env: any, ctx: ExecutionContext) {
    switch (controller.cron) {
      // Every minute — drains the upload-notification and NAS-sweep queues.
      case '* * * * *':
        ctx.waitUntil(triggerCronRoute('/api/cron/tick-queues', env, ctx));
        // Files & Drive: index reconcile/backfill, trash retention, video
        // preview jobs. Its own route so a slow step there can't delay the
        // upload/NAS queues above.
        ctx.waitUntil(triggerCronRoute('/api/cron/drive-tick', env, ctx));
        break;

      // Every Saturday — populates the weekly NAS backup sweep queue.
      case '0 20 * * 6':
        ctx.waitUntil(triggerCronRoute('/api/cron/nas-weekly-sweep', env, ctx));
        break;

      // 1st of the month — auto-creates each client's monthly shoot-day
      // quota (Client.shootDaysPerMonth) as fresh Shoot rows for the
      // videographer. Guarded by a per-(client, month) unique row so a
      // double-fire can't create duplicate shoots.
      case '0 5 1 * *':
        ctx.waitUntil(triggerCronRoute('/api/cron/generate-monthly-shoots', env, ctx));
        break;

      // Nightly — Daily Team Summary report (email + ops Slack channel).
      // Original cron-master.ts schedule was '5 19 * * *' in America/New_York
      // (7:05 PM ET). Cloudflare Cron Triggers are UTC-only; we use 23:00 UTC
      // to match ≈ 7:00 PM EDT (same convention as the billing crons below).
      // During EST this fires at 6:00 PM ET — still within the report window.
      // Keep '0 0 * * *' as a no-op-safe alias in case an old trigger remains.
      case '0 23 * * *':
      case '0 0 * * *':
        ctx.waitUntil(triggerCronRoute('/api/reports/daily-summary', env, ctx));
        break;

      // Pre-existing placeholder schedule (0 9 * * *) — not wired to
      // anything yet (see /areas/cloudflare-migration.md). Left as a
      // deliberate no-op so this switch doesn't error when it fires; wire
      // this up when whatever it was meant for goes live.
      // Auto-invoice — daily ≈ 9:00 AM America/New_York (13:00 UTC during EDT).
      case '0 13 * * *':
        ctx.waitUntil(triggerCronRoute('/api/cron/auto-invoice', env, ctx));
        break;

      // Enforce portal locks — daily ≈ 9:15 AM ET (after auto-invoice).
      case '15 13 * * *':
        ctx.waitUntil(triggerCronRoute('/api/cron/enforce-portal-locks', env, ctx));
        break;

      // Billing warning emails — daily ≈ 10:00 AM ET (clients due in 3 days).
      case '0 14 * * *':
        ctx.waitUntil(triggerCronRoute('/api/cron/billing-warnings', env, ctx));
        break;

      // Auto-invoice day-before review — ≈ 10:30 AM ET (notify Eric to review settings).
      case '30 14 * * *':
        ctx.waitUntil(triggerCronRoute('/api/cron/auto-invoice-review-reminder', env, ctx));
        break;

      // Automatic Stripe reconciliation — hourly. Replaces relying on someone
      // remembering to click "Sync & Refresh"; webhooks handle real-time
      // updates, this is just the safety net for anything one missed.
      case '0 * * * *':
        ctx.waitUntil(triggerCronRoute('/api/cron/billing-sync', env, ctx));
        break;

      // Tech Fee failure retry sweep — hourly, offset 15m past billing-sync
      // so they don't both fire on the same minute. Retries any Tech Fee
      // whose Stripe balance_transaction fee still wasn't available even
      // after captureTechFeeFromCharge's own immediate retry.
      case '15 * * * *':
        ctx.waitUntil(triggerCronRoute('/api/cron/tech-fee-retry', env, ctx));
        break;

      // Windsor.ai social analytics — daily, pulls the previous day's
      // Instagram/Facebook/TikTok/YouTube stats for every active
      // SocialAccount into SocialAnalytics.
      case '5 5 * * *':
        ctx.waitUntil(triggerCronRoute('/api/cron/windsor-sync', env, ctx));
        break;

      default:
        console.log(`[worker.ts] Cron fired with no handler wired: ${controller.cron}`);
    }
  },

  // Consumer for the `notifications`, `zip-jobs` and `drive-events` Cloudflare Queues
  // (see wrangler.toml's [[queues.consumers]]) — Cloudflare routes a batch
  // from whichever queue triggered this invocation; `batch.queue` tells us
  // which one so a single handler can serve both.
  //
  // notifications: every Slack message and email in the app is enqueued
  // via src/lib/notification-queue.ts's enqueueNotification() and lands
  // here for actual delivery. Slack jobs are delivered directly (plain
  // HTTPS, fine on Workers); email jobs are relayed to e8-file-server,
  // since Workers can't open raw SMTP sockets.
  //
  // zip-jobs: "Download All" zip-build jobs, enqueued via
  // src/lib/zip-jobs-queue.ts's enqueueZipJob(). deliverZipJob() awaits
  // the file-server's full response, which can legitimately take HOURS
  // for a 100GB folder — safe here specifically because Cloudflare Queue
  // consumer invocations have no wall-time limit, unlike a plain HTTP
  // fetch handler. Never call deliverZipJob() from an API route directly.
  async queue(batch: MessageBatch<NotificationJob | ZipJobMessage | R2EventMessage>, env: any, ctx: ExecutionContext) {
    // drive-events: R2 event notifications (object-create / object-delete on
    // e8-app-r2-prod) that keep the Files & Drive index in Postgres current.
    // Applied as one batch — applyR2Events is idempotent and tolerates
    // duplicates/out-of-order delivery, so a whole-batch retry is safe.
    if (batch.queue === 'drive-events') {
      try {
        await applyR2Events(batch.messages.map((m: { body: unknown }) => m.body as R2EventMessage), env);
        batch.ackAll();
      } catch (err: any) {
        console.error(`[worker.ts] drive-events batch failed (${batch.messages.length} msgs):`, err?.message || err);
        batch.retryAll();
      }
      return;
    }

    if (batch.queue === 'zip-jobs') {
      for (const message of batch.messages) {
        try {
          await deliverZipJob(message.body as ZipJobMessage, env);
          message.ack();
        } catch (err: any) {
          console.error(`[worker.ts] Zip job failed (jobId=${(message.body as ZipJobMessage).jobId}):`, err?.message || err);
          // Not retried: a failed multi-hour job re-running from scratch on
          // the same queue-retry backoff is rarely what the user wants —
          // the frontend already surfaces the failure and offers a fresh
          // "Download All" click, which enqueues a brand-new job.
          message.ack();
        }
      }
      return;
    }

    for (const message of batch.messages) {
      try {
        const job = message.body as NotificationJob;
        if (job.kind === 'email') {
          await deliverEmailJobNow(job, env);
        } else {
          await deliverSlackJobNow(job);
        }
        message.ack();
      } catch (err: any) {
        console.error(`[worker.ts] Notification job failed (kind=${(message.body as NotificationJob).kind}):`, err?.message || err);
        message.retry();
      }
    }
  },
};