// worker.ts (project root)
//
// The Worker generated by @opennextjs/cloudflare (.open-next/worker.js)
// only exports a `fetch` handler — no `scheduled` handler, so Cron Triggers
// configured in wrangler.toml previously had nothing listening for them.
// This is OpenNext's documented "Custom Worker" pattern: re-export the
// generated fetch handler unchanged, and add our own scheduled() alongside
// it. See: https://opennext.js.org/cloudflare/howtos/custom-worker
//
// Deliberately minimal and dependency-free — all real logic lives in Next.js
// API routes (self-fetched over plain HTTPS with the existing x-cron-secret
// auth pattern already used by every other /api/cron/* route), not here.
// Keeping this file trivial matters: it's the app's actual deployment entry
// point (wrangler.toml's `main`), so a bug here can break the whole app,
// not just one feature.

// @ts-ignore — .open-next/worker.js is generated at build time
import { default as handler } from './.open-next/worker.js';

const APP_URL = 'https://e8productions.com';

async function triggerCronRoute(path: string, env: any): Promise<void> {
  try {
    const res = await fetch(`${APP_URL}${path}`, {
      method: 'POST',
      headers: { 'x-cron-secret': env.CRON_SECRET || '' },
    });
    if (!res.ok) {
      console.error(`[worker.ts] ${path} returned ${res.status}: ${await res.text().catch(() => '')}`);
    }
  } catch (err: any) {
    console.error(`[worker.ts] ${path} failed:`, err.message || err);
  }
}

export default {
  fetch: handler.fetch,

  async scheduled(controller: ScheduledController, env: any, ctx: ExecutionContext) {
    switch (controller.cron) {
      // Every minute — drains the upload-notification and NAS-sweep queues.
      case '* * * * *':
        ctx.waitUntil(triggerCronRoute('/api/cron/tick-queues', env));
        break;

      // Every Saturday — populates the weekly NAS backup sweep queue.
      case '0 20 * * 6':
        ctx.waitUntil(triggerCronRoute('/api/cron/nas-weekly-sweep', env));
        break;

      // Pre-existing placeholder schedules (0 9 * * *, 0 0 * * *) — not
      // wired to anything yet (see /areas/cloudflare-migration.md). Left as
      // a deliberate no-op so this switch doesn't error when they fire;
      // wire these up here when whatever they were meant for goes live.
      default:
        console.log(`[worker.ts] Cron fired with no handler wired: ${controller.cron}`);
    }
  },
};