export const dynamic = 'force-dynamic';

// POST /api/cron/auto-invoice
// Called daily by cron-master.ts
// Finds clients whose billingDay = today, creates a DRAFT invoice,
// then sends a Slack DM to Sahil and Eric to review before anything goes to clients.

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import {
  generateInvoiceNumber,
  getOrCreateStripeCustomer,
  createStripeInvoice,
  toCents,
} from '@/lib/stripe';
import { sendSlackDM } from '@/lib/slack';

// The two people who should receive the review DM
const REVIEWER_NAMES = ['Sahil Sagvekar', 'Eric Davis'];

export async function POST(req: NextRequest) {
  // Verify cron secret
  const cronSecret = req.headers.get('x-cron-secret');
  if (cronSecret !== process.env.CRON_SECRET) {
    return NextResponse.json({ ok: false, message: 'Unauthorized' }, { status: 401 });
  }

  const today = new Date();
  const todayDay = today.getDate();
  const monthName = today.toLocaleDateString('en-US', { month: 'long' });
  const year = today.getFullYear();
  const monthLabel = `${monthName} ${year}`;

  console.log(`📄 [Auto-Invoice] Running for day ${todayDay} (${monthLabel})`);

  // Fetch all active clients
  const clients = await prisma.client.findMany({
    where: { status: 'active' },
    select: {
      id: true,
      name: true,
      companyName: true,
      email: true,
      billing: true,
    },
  });

  const results: {
    clientName: string;
    status: 'created' | 'skipped';
    reason?: string;
    invoiceNumber?: string;
    amount?: string;
    invoiceId?: string;
  }[] = [];

  for (const client of clients) {
    const billing = client.billing as any;
    const clientName = client.companyName || client.name;

    // Skip if no billing config
    if (!billing?.monthlyFee || !billing?.billingDay) {
      results.push({ clientName, status: 'skipped', reason: 'No billing config' });
      continue;
    }

    const monthlyFee = parseFloat(billing.monthlyFee);
    if (isNaN(monthlyFee) || monthlyFee <= 0) {
      results.push({ clientName, status: 'skipped', reason: 'Invalid monthly fee' });
      continue;
    }

    // Check if billingDay matches today
    const billingDay = parseInt(billing.billingDay);
    if (billingDay !== todayDay) {
      results.push({ clientName, status: 'skipped', reason: `Billing day is ${billingDay}, today is ${todayDay}` });
      continue;
    }

    // Check not already invoiced this month
    const startOfMonth = new Date(year, today.getMonth(), 1);
    const endOfMonth = new Date(year, today.getMonth() + 1, 0, 23, 59, 59);

    const existingInvoice = await prisma.invoice.findFirst({
      where: {
        stripeCustomer: { clientId: client.id },
        createdAt: { gte: startOfMonth, lte: endOfMonth },
      },
      select: { id: true, invoiceNumber: true },
    });

    if (existingInvoice) {
      results.push({
        clientName,
        status: 'skipped',
        reason: `Already invoiced this month (${existingInvoice.invoiceNumber})`,
      });
      continue;
    }

    try {
      const stripeCustomer = await getOrCreateStripeCustomer(
        client.id,
        client.email,
        clientName
      );

      const dbStripeCustomer = await prisma.stripeCustomer.findUnique({
        where: { stripeCustomerId: stripeCustomer.id },
      });

      if (!dbStripeCustomer) {
        results.push({ clientName, status: 'skipped', reason: 'Failed to create Stripe customer' });
        continue;
      }

      const amountCents = toCents(monthlyFee);
      const lineItems = [{
        description: `Monthly Retainer — ${monthLabel}`,
        amount: amountCents,
        quantity: 1,
      }];

      const invoiceNumber = generateInvoiceNumber();
      const dueDate = new Date(today.getTime() + 30 * 24 * 60 * 60 * 1000);

      // metadata must be Record<string, string> — no booleans
      const stripeInvoice = await createStripeInvoice(
        stripeCustomer.id,
        lineItems.map(item => ({
          description: item.description,
          amount: item.amount * item.quantity,
        })),
        30,
        {
          invoiceNumber,
          clientId: client.id,
          invoiceType: 'STANDARD',
          autoGenerated: 'true', // string, not boolean
          monthLabel,
        },
        `Monthly retainer for ${clientName} — ${monthLabel}`
      );

      // Save as DRAFT — NOT sent to client yet
      const invoice = await prisma.invoice.create({
        data: {
          stripeCustomerId: dbStripeCustomer.id,
          stripeInvoiceId: stripeInvoice.id,
          invoiceNumber,
          status: 'DRAFT',
          amount: amountCents,
          currency: 'usd',
          dueDate,
          description: `Monthly retainer for ${clientName} — ${monthLabel}`,
          lineItems,
          notes: billing.notes || null,
          sentAt: null,
          metadata: {
            invoiceType: 'STANDARD',
            autoGenerated: true,
            monthLabel,
          },
        },
      });

      console.log(`✅ [Auto-Invoice] Draft created for ${clientName}: ${invoiceNumber} ($${monthlyFee})`);

      results.push({
        clientName,
        status: 'created',
        invoiceNumber,
        amount: `$${monthlyFee.toFixed(2)}`,
        invoiceId: invoice.id,
      });
    } catch (err: any) {
      console.error(`❌ [Auto-Invoice] Failed for ${clientName}:`, err.message);
      results.push({ clientName, status: 'skipped', reason: `Error: ${err.message}` });
    }
  }

  const created = results.filter(r => r.status === 'created');
  const skipped = results.filter(r => r.status === 'skipped' && !r.reason?.startsWith('Billing day is'));

  console.log(`📄 [Auto-Invoice] Done. Created: ${created.length}, Skipped: ${skipped.length}`);

  // Send Slack DMs to reviewers if any drafts were created
  if (created.length > 0) {
    const APP_URL = process.env.BASE_URL || process.env.NEXTAUTH_URL || 'https://e8productions.com';
    const billingUrl = `${APP_URL}/billing/invoices?status=DRAFT`;

    const reviewerUsers = await prisma.user.findMany({
      where: { name: { in: REVIEWER_NAMES } },
      select: { id: true, name: true, slackUserId: true },
    });

    const invoiceLines = created
      .map(c => `• *${c.clientName}* — ${c.invoiceNumber} · ${c.amount}`)
      .join('\n');

    const skippedNote = skipped.length > 0
      ? `\n\n_Skipped ${skipped.length} client(s) — no billing config or already invoiced this month._`
      : '';

    const message =
      `🧾 *${created.length} invoice draft${created.length !== 1 ? 's' : ''} ready for review — ${monthLabel}*\n\n` +
      `${invoiceLines}${skippedNote}\n\n` +
      `Nothing has been sent to clients yet. Review and send when ready:\n` +
      `<${billingUrl}|Review Invoices →>`;

    for (const reviewer of reviewerUsers) {
      if (!reviewer.slackUserId) {
        console.warn(`[Auto-Invoice] ${reviewer.name} has no slackUserId — skipping DM`);
        continue;
      }
      try {
        await sendSlackDM(reviewer.slackUserId, {
          type: 'info',
          title: 'Invoices Ready for Review',
          message,
        });
        console.log(`✅ [Auto-Invoice] Slack DM sent to ${reviewer.name}`);
      } catch (err: any) {
        console.error(`❌ [Auto-Invoice] Failed to DM ${reviewer.name}:`, err.message);
      }
    }
  }

  return NextResponse.json({
    ok: true,
    message: `Auto-invoice complete. ${created.length} draft(s) created, ${skipped.length} skipped.`,
    created,
    skipped,
  });
}