export const dynamic = 'force-dynamic';
// src/app/api/drive/preview/route.ts
//
// Video preview state for the Drive player.
//   GET  ?k=<key>  -> { status, playlist?, sprites?, durationSeconds, width, height, progress? }
//   POST { key }   -> ask for a preview now (jumps the queue); returns the new status
// Previews are 720p HLS + a scrub sprite, generated by the file server's
// transcoder (see src/lib/drive/preview-jobs.ts). Until one is ready the
// player plays the original file.

import { NextRequest, NextResponse } from 'next/server';
import { sql } from 'drizzle-orm';
import { getCloudflareContext } from '@opennextjs/cloudflare';
import { getCurrentUser2 } from '@/lib/auth';
import { getDbHttp } from '@/lib/db';
import { userCanAccessKey } from '@/lib/drive/access';
import { isDrivePreviewsEnabled } from '@/lib/drive/index-store';
import { requestPreview } from '@/lib/drive/preview-jobs';
import { signedHlsUrls } from '@/lib/drive/url-tokens';
import { getHlsJobStatus } from '@/lib/file-server';

async function describe(key: string) {
  const res = await getDbHttp().execute(sql`
    SELECT "previewStatus", "previewPrefix", "previewError", "durationSeconds", "width", "height", "storageTier"
    FROM "DriveItem" WHERE "key" = ${key} AND "removedAt" IS NULL LIMIT 1
  `);
  const row = (res as any).rows?.[0];
  if (!row) return { status: 'unknown' as const, enabled: isDrivePreviewsEnabled() };
  const out: Record<string, unknown> = {
    status: row.previewStatus,
    enabled: isDrivePreviewsEnabled(),
    storageTier: row.storageTier,
    durationSeconds: row.durationSeconds ?? null,
    width: row.width ?? null,
    height: row.height ?? null,
    error: row.previewStatus === 'failed' ? row.previewError : null,
  };
  if (row.previewStatus === 'ready' && row.previewPrefix) {
    Object.assign(out, await signedHlsUrls(key, row.previewPrefix));
  } else if (row.previewStatus === 'processing') {
    try {
      const { env } = getCloudflareContext();
      const s = await getHlsJobStatus(env, key);
      if (typeof s.progress === 'number') out.progress = s.progress;
    } catch {
      /* progress is best-effort */
    }
  }
  return out;
}

async function guard(req: NextRequest, key: string): Promise<NextResponse | null> {
  if (!key) return NextResponse.json({ error: 'Missing key' }, { status: 400 });
  const user = await getCurrentUser2(req);
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  if (!(await userCanAccessKey(user, key))) return NextResponse.json({ error: 'Not allowed' }, { status: 403 });
  return null;
}

export async function GET(req: NextRequest) {
  const key = req.nextUrl.searchParams.get('k') || '';
  const denied = await guard(req, key);
  if (denied) return denied;
  try {
    return NextResponse.json(await describe(key));
  } catch (err: any) {
    return NextResponse.json({ status: 'unknown', enabled: false, error: err?.message }, { status: 200 });
  }
}

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));
  const key = String(body?.key || '');
  const denied = await guard(req, key);
  if (denied) return denied;
  if (!isDrivePreviewsEnabled()) return NextResponse.json({ status: 'none', enabled: false });
  try {
    await requestPreview(key);
    return NextResponse.json(await describe(key));
  } catch (err: any) {
    return NextResponse.json({ error: err?.message || 'Could not request preview' }, { status: 500 });
  }
}
