-- SUPERSEDED by drizzle/0001_split_rejected_statuses.sql
-- That migration splits TaskStatus into REJECTED_BY_QC / REJECTED_BY_CLIENT
-- (and backfills existing REJECTED rows to REJECTED_BY_QC) instead of adding
-- a separate rejectedBy column.
-- Kept for historical reference only — do not run.
